version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
      - pip install aws-sam-cli
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam package --template-file .aws-sam/build/template.yaml --output-template-file packaged.yaml --s3-bucket arn:aws:s3:::codepipeline-eu-west-3-737397133459

artifacts:
  files:
    - packaged.yaml
