version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt -t build/

  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket codedeploy-eu-west-3-344520032411 --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
