version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt -t build/

  build:
    commands:
      - cp -R . build/
      - aws cloudformation package --template-file template.yaml --s3-bucket my-sam-bucket --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
