AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend Python for Bips App

Resources:
  BipsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bips.lambda_handler
      Runtime: python3.8
      Events:
        CreateBip:
          Type: Api
          Properties:
            Path: /bips
            Method: post
        GetBips:
          Type: Api
          Properties:
            Path: /bips
            Method: get

Outputs:
  ApiGatewayUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bips/"
