AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend Python for Bips App

Resources:
  BipsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Events:
        CreateBip:
          Type: Api
          Properties:
            Path: /bips
            Method: post
        GetBips:
          Type: Api
          Properties:
            Path: /bips
            Method: get

Outputs:
  ApiGatewayUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bips/"
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend Python for Bips App

Resources:
  BipsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          BIPS_TABLE: !Ref BipsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BipsTable
      Events:
        CreateBip:
          Type: Api
          Properties:
            Path: /bips
            Method: post
        GetBips:
          Type: Api
          Properties:
            Path: /bips
            Method: get

  BipsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Bips
      AttributeDefinitions:
        - AttributeName: location
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: location
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  BipsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: '2.0'
        info:
          title: Bips API
        paths:
          /bips:
            post:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BipsFunction.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
            get:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BipsFunction.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy

  BipsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-bips-bucket

Outputs:
  ApiGatewayUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${BipsApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bips/"
  BipsBucketArn:
    Description: "Bips S3 Bucket ARN"
    Value: !GetAtt BipsBucket.Arn
